### ISSUE TITLE
LVGL 9.0 compatibility

### ISSUE THREAD

**Issue by m0vse** [jakpaul/lvgl_touch_calibration#6]
Now that LVGL 9.0 has been released, any plans to make this compatible? There are significant API changes!

https://docs.lvgl.io/master/CHANGELOG.html#important

Phil

**Comment by jakpaul** [comment]
Yes, this project will be migrated to 9.0. Relevant are mainly the indev API changes. The only thing keeping me from working on it is that I have little time to spare right now. But I will look into it as soon as I can.

**Comment by jakpaul** [comment]
Changes are done and verified, so I will close this. Feel free to reopen if there are any issues with the new version. Since LVGL updated just recently, conflicting changes might still happen.
I would be happy to hear feedback on this.
